CREATE TABLE IF NOT EXISTS academic_certificates (
    id INT NOT NULL AUTO_INCREMENT,
    student_id INT NOT NULL,
    programme_id INT NOT NULL,
    certificate_number VARCHAR(64) NOT NULL,
    verification_token CHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'draft',
    eligibility_snapshot LONGTEXT NOT NULL,
    requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    requested_by_user_id INT NULL,
    submitted_at DATETIME NULL,
    issued_at DATETIME NULL,
    issued_by_user_id INT NULL,
    revoked_at DATETIME NULL,
    revoked_by_user_id INT NULL,
    revocation_reason VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY academic_certificates_number_unique (certificate_number),
    UNIQUE KEY academic_certificates_token_unique (verification_token),
    KEY academic_certificates_student_index (student_id),
    KEY academic_certificates_programme_index (programme_id),
    KEY academic_certificates_status_index (status),
    CONSTRAINT academic_certificates_student_fk FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT academic_certificates_programme_fk FOREIGN KEY (programme_id) REFERENCES academic_programmes(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT academic_certificates_requested_by_fk FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT academic_certificates_issued_by_fk FOREIGN KEY (issued_by_user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT academic_certificates_revoked_by_fk FOREIGN KEY (revoked_by_user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
